name: Node.js Package

# 触发工作流程的事件
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

# 按顺序运行作业
jobs:
  publish-npmjs:
    # 指定的运行器环境
    runs-on: ubuntu-latest
    # 设置 node 版本
    strategy:
      matrix:
        node-version: [20]
    steps:
      # 拉取 github 仓库代码
      - uses: actions/checkout@v3
      # 设定 node 环境
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # 默认配置，如果不配置将影响publish
          registry-url: https://registry.npmjs.org/
      - run: npm install -g pnpm # 安装 PNPM
      # 安装依赖，相当于 npm ci
      - name: Install dependencies
        run: pnpm install --frozen-lockfile # 根据 lock 文件安装依赖
      # 执行构建步骤
      - name: 构建
        run: |
          pnpm run build
      # 执行部署步骤
      - name: 部署
        # 默认配置
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # 在第三步中设置的 ACCESS_TOKEN
          ACCESS_TOKEN: ${{ secrets.YUPPIE_UI_TOKEN }}
          # 指定推送到的远程分支
          BRANCH: pages
          # 指定构建之后的产出路径
          FOLDER: build
      - run: npm publish
        env:
          # 在第三步中设置的 NPM_TOKEN
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: publish 成功通知
        run: echo npm 推送成功，请访问 https://changweihua.github.io

      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version

      - name: 创建 GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.YUPPIE_UI_TOKEN }}
        with:
          tag_name: v${{steps.version.outputs.value}}
          release_name: v${{steps.version.outputs.value}}
          draft: false
          prerelease: false
